### ISSUE TITLE
node16 update

### ISSUE THREAD

**Issue by atamgp** [RyanSiu1995/kubebuilder-action#13]
Please update this?

runs:
  using: 'node12'

node 12 is deprecated, thanks!

**Comment by RyanSiu1995** [comment]
Will do the update later this week.
Thank you for reporting.

**Comment by RyanSiu1995** [comment]
Hi @atamgp, the patch is release through v1.3.0.
Please have an update on your workflow to see if there is any breakage.

**Comment by atamgp** [comment]
thanks a lot, looks good!
