### ISSUE TITLE
Adapt action for version 3.0.0 of Kubebuilder

### ISSUE THREAD

**Issue by fspaniol** [RyanSiu1995/kubebuilder-action#6]
I was trying to use the action today to install version 3.0.0, and it's throwing an error because the download now comes as a binary instead of a compressed file.

**Comment by RyanSiu1995** [comment]
Hi @fspaniol, please use v1.2 for kubebuilder 3.0.0. If you encounter any issue, please feel free to reopen this issue.

**Comment by fspaniol** [comment]
Hi @RyanSiu1995 , thanks a lot! It works :)

I'd just suggest to be careful because the kube-apiserver binary doesn't exist for all k8s version for darwin.

The way I worked around this was following this script: https://github.com/kubernetes-sigs/cluster-api/blob/95fe9e2c2c48cb7c765e40fe97861f22765441ff/scripts/fetch_ext_bins.sh#L89
