### ISSUE TITLE
Kubebuilder 2.3.1 installation no longer working

### ISSUE THREAD

**Issue by fspaniol** [RyanSiu1995/kubebuilder-action#8]
It seems that the files required to install <3.0.0 versions are no longer there, therefore the action fails when trying to install them.

**Comment by RyanSiu1995** [comment]
Hi @fspaniol , do you have any logs or example for me?
I want to make sure the patch can be correctly fixed your issue

**Comment by zwtop** [comment]
Caused by https://github.com/kubernetes-sigs/kubebuilder/issues/2311

**Comment by RyanSiu1995** [comment]
@zwtop and @fspaniol, thank for reporting and working on this.
I have released v1.2.1 so please use it for your workflow.
Please open up an issue if you see there is an issue again.
Thank you!
